from typing import (
    Any,
    Callable,
    Dict,
    Generator,
    List,
    Literal,
    Iterable,
    Mapping,
    Optional,
    Sequence,
    Tuple,
    Type,
    TypeVar,
    Union,
    overload
)

class Entity:
    def to_string(self) -> str: ...
    def toString(self) -> str: ...
    def __str__(self) -> str: ...
    def __iter__(self):
    def __getitem__(self, index: Union[list, tuple]) -> Entity: ... #can take also other than tuple, list
    def get(self, *index):
    def find(self, index: Union[list, tuple]) -> Union[Entity, None]: ... #can take also other than tuple, list
    def instances(self):
    def name(self) -> str: ...
    def indexarity(self) -> int: ...
    def is_scalar(self) -> bool: ...
    def isScalar(self) -> bool: ...
    def num_instances(self) -> int: ...
    def numInstances(self) -> int: ...
    def get_indexing_sets(self):
    def xref(self) -> list: ... # list of strings
    def get_values(self, suffixes=None):
    def to_pandas(self, **kwargs):
    def to_dict(self, **kwargs):
    def to_list(self, **kwargs):
    def set_values(self, data):
    # Aliases
    getIndexingSets = get_indexing_sets
    getValues = get_values
    setValues = set_values

class Constraint(Entity):
    def __setitem__(self, index, value):
    def is_logical(self) -> bool: ...
    def isLogical(self) -> bool: ...
    def isLogical(self) -> bool: ...
    def drop(self) -> None: ...
    def restore(self) -> None: ...
    def body(self) -> float: ...
    def astatus(self) -> str: ...
    def defvar(self) -> int: ...
    def dinit(self) -> float: ...
    def dinit0(self) -> float: ...
    def dual(self) -> float: ...
    def lb(self) -> float: ...
    def ub(self) -> float: ...
    def lbs(self) -> float: ...
    def ubs(self) -> float: ...
    def ldual(self) -> float: ...
    def udual(self) -> float: ...
    def lslack(self) -> float: ...
    def uslack(self) -> float: ...
    def slack(self) -> float: ...
    def sstatus(self) -> str: ...
    def status(self) -> str: ...
    def set_dual(self, dual: Union[int, float]) -> None: ...
    def setDual(self, dual: Union[int, float]) -> None: ...
    def val(self) -> Union[float, None]: ...

class Objective(Entity):
    def value(self) -> float: ...
    def astatus(self) -> str: ...
    def sstatus(self) -> str: ...
    def exitcode(self) -> int: ...
    def message(self) -> str: ...
    def result(self) -> str: ...
    def drop(self) -> None: ...
    def restore(self) -> None: ...
    def minimization(self) -> bool: ...

class Parameter:
    def __setitem__(self, index, value):
    def is_symbolic(self) -> bool: ...
    def isSymbolic(self) -> bool: ...
    def has_default(self) -> bool: ...
    def hasDefault(self) -> bool: ...
    def __getitem__(self, index):
    def value(self):
    def set(self, *args):
    def set_values(self, values):
    # Aliases
    setValues = set_values

class Set:
    def __setitem__(self, index, value):
    def __iter__(self):
    def instances(self):
    def arity(self):
    def get_values(self):
    def members(self):
    def size(self):
    def contains(self, t):
    def set_values(self, values):
    # Aliases
    getValues = get_values
    setValues = set_values

class Variable(Entity):
    def __setitem__(self, index, value):
    def value(self) -> float: ...
    def fix(self, value: Optional[float] = None) -> None: ...
    def unfix(self) -> None: ...
    def set_value(self, value: Union[float, int, Parameter]) -> None: ...
    def setValue(self, value: Union[float, int, Parameter]) -> None: ...
    def astatus(self) -> str: ...
    def defeqn(self) -> int: ...
    def dual(self) -> float: ...
    def init(self) -> float: ...
    def init0(self) -> float: ...
    def lb(self) -> float: ...
    def ub(self) -> float: ...
    def lb0(self) -> float: ...
    def ub0(self) -> float: ...
    def lb1(self) -> float: ...
    def ub1(self) -> float: ...
    def lb2(self) -> float: ...
    def ub2(self) -> float: ...
    def lrc(self) -> float: ...
    def urc(self) -> float: ...
    def lslack(self) -> float: ...
    def uslack(self) -> float: ...
    def rc(self) -> float: ...
    def slack(self) -> float: ...
    def sstatus(self) -> str: ...
    def status(self) -> str: ...


class Environment:
    def __str__(self) -> str: ...
    def __iter__(self):
    def __setitem__(self, name: str, value: str) -> None: ...
    def __getitem__(self, name: str) -> Union[str, None]: ...
    def to_string(self) -> str: ...
    def set_bin_dir(self, binary_directory: str) -> None: ...
    def get_bin_dir(self) -> str: ...
    def set_bin_name(self, binary_name: str) -> None: ... #should also work with Path
    def get_bin_name(self) -> str: ...

class AMPL:
    var = property(_var)
    con = property(_con)
    obj = property(_obj)
    set = property(_set)
    param = property(_param)
    option = property(_option, _set_option)
    def __init__(self, environment: Optional[Environment] = None) -> None: ...
    def get_data(self, statements: Sequence[str]) -> Dataframe: ...
    def get_entity(self, name: str) -> Entity: ...
    def get_variable(self, name: str) -> Variable: ...
    def get_constraint(self, name: str) -> Constraint: ...
    def get_objective(self, name: str) -> Objective: ...
    def get_set(self, name: str) -> Set: ...
    def get_parameter(self, name: str) -> Parameter: ...
    def eval(self, statements):
    def get_output(self, statements):
    def reset(self) -> None: ...
    def close(self) -> None: ...
    def is_running(self) -> bool: ...
    def solve(self, problem="", solver="", verbose=True, return_output=False, **kwargs):
    def cd(self, path: Optional[str] = None) -> str: ... # should also except Path as path
    def set_option(self, name: str, value: Union[bool, int, float, str]) -> None: ...
    def get_option(self, name: str) -> Union[bool, int, float, str]: ...
    def read(self, filename: str) -> None: ... # might also include path - look it up
    def read_data(self, filename: str) -> None: ... # same as above
    def get_value(self, scalar_expression):
    def set_data(self, data, set_name=None):
    def read_table(self, table_name):
    def write_table(self, table_name):
    def display(self, *ampl_expressions):
    def set_output_handler(self, output_handler):
    def set_error_handler(self, error_handler):
    def get_output_handler(self):
    def get_error_handler(self):
    def get_variables(self):
    def get_constraints(self):
    def get_objectives(self):
    def get_sets(self):
    def get_parameters(self):
    def get_current_objective(self):
    def _var(self):
    def _con(self):
    def _obj(self):
    def _set(self):
    def _param(self):
    def _option(self):
    def _set_option(self, options_dict):
    def export_model(self, filename=""):
    def export_data(self, filename=""):
    def snapshot(self, filename="", model=True, data=True, options=True):
    def write(self, filename, auxfiles=""):
    def solve_result(self):
    def solve_result_num(self):
    def get_iis(self, flat=True):
    def get_solution(self, flat=True, zeros=False):
    def _start_recording(self, filename):
    def _stop_recording(self):
    def _load_session(self, filename):
    def to_ampls(self, driver, options=None):
    def import_ampls_solution(self, model, number=None, import_entities=False, keep_files=False):
    def to_string(self) -> str: ...
    def __str__(self) -> str: ...
    # Aliases
    _loadSession = _load_session
    _startRecording = _start_recording
    _stopRecording = _stop_recording
    exportData = export_data
    exportModel = export_model
    getConstraint = get_constraint
    getConstraints = get_constraints
    getCurrentObjective = get_current_objective
    getData = get_data
    getEntity = get_entity
    getErrorHandler = get_error_handler
    getObjective = get_objective
    getObjectives = get_objectives
    getOption = get_option
    getOutput = get_output
    getOutputHandler = get_output_handler
    getParameter = get_parameter
    getParameters = get_parameters
    getSet = get_set
    getSets = get_sets
    getValue = get_value
    getVariable = get_variable
    getVariables = get_variables
    isRunning = is_running
    readData = read_data
    readTable = read_table
    setData = set_data
    setErrorHandler = set_error_handler
    setOption = set_option
    setOutputHandler = set_output_handler
    toString = to_string
    writeTable = write_table
