from . import amplpython

class AMPLException(amplpython.AMPLException):
    """
    Represent an exception generated by AMPL.
    """
    def __init__(self, _impl):
        self._impl = _impl

    def getSourceName(self):
        """
        Get the name of the file where the error was detected.
        """
        return self._impl.getSourceName()

    def getLineNumber(self):
        """
        Get the row where the error is located.
        """
        return self._impl.getLineNumber()

    def getOffset(self):
        """
        Get the offset where the error is located.
        """
        return self._impl.getOffset()

    def getMessage(self):
        """
        Get the error message.
        """
        return self._impl.getMessage()
